room_slot/booking/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('',views.index,name='index'),
    path('contact-us',views.contact,name='contact-us'),
    path('login',views.user_login,name='user_login'),
    path('signup',views.user_signup,name='user_signup'),
    path('book_hotel',views.book_hotel,name='book_hotel'),
    path('book/<str:id>',views.book,name='book'),
    path('book_now',views.book_now,name='book_now'),
    path('confirm-now-booking',views.book_confirm,name="book_confirm"),
    path('login1',views.guest_signup,name='guest_login'),
    path('cancel-room/<str:id>',views.cancel_room,name='cancel-room'),
    path('dashboard/',views.user_dashboard,name='user_dashboard'),
    path('dashboard1/',views.guest_dashboard,name='guest_dashboard'),
    ]

room_slot/room_slot/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from booking import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('booking.urls')),
    path('user/',include('booking.urls')),
    path('guest/',include('booking.urls')),
    path('logout',views.logout,name='logout')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

room_slot/booking/models.py
from django.db import models
from customer.models import Guest
from datetime import date
from room.models import Hotel,Room,Room_type,Service
class Contact(models.Model):
    name=models.CharField(max_length=100)
    email=models.CharField(max_length=100)
    message=models.TextField(max_length=2000)
    def __str__(self):
        return self.name
'''
class RoomImage(models.Model):
    room=models.ForeignKey(Rooms, on_delete=models.CASCADE)
    room_image=models.ImageField(upload_to="media", height_field=None, width_field=None, max_length=None)
'''
class Booking(models.Model):
    book_no=models.AutoField(primary_key=True)
    gid=models.ForeignKey(Guest,on_delete=models.CASCADE)
    plantypechoices=(('A','A'),('B','B'),('C','C'),)
    plantype=models.CharField(max_length=1,choices=plantypechoices)
    hid=models.ForeignKey(Hotel,on_delete=models.CASCADE)
    checkin=models.DateField(auto_now=False,auto_now_add=False)
    checkout=models.DateField(auto_now=False,auto_now_add=False)
    cost=models.IntegerField()
    @property
    def is_past_due(self):
        return date.today()>self.checkout
class Booking_detail(models.Model):
    book_no=models.ForeignKey(Booking,on_delete=models.CASCADE)
    book_dtno=models.IntegerField()
    rno=models.ForeignKey(Room,on_delete=models.CASCADE,blank=True,null=True)
    rtype=models.ForeignKey(Room_type,on_delete=models.CASCADE)
    sid=models.ForeignKey(Service,on_delete=models.CASCADE,default="",null=True,blank=True)
    adult=((0,'0'),(1,'1'),(2,'2'),)
    No_adults=models.IntegerField(choices=adult)
    children=((0,'0'),(1,'1'),)
    No_children=models.IntegerField(choices=children)
    class Meta(object):
        constraints=[
        models.UniqueConstraint(fields=['book_no','book_dtno'],name='unique_together')]
class Service_in_room(models.Model):        
    sid=models.ForeignKey(Service,on_delete=models.CASCADE)
    book_dtno=models.ForeignKey(Booking_detail,on_delete=models.CASCADE)
    class Meta(object):
        constraints=[
        models.UniqueConstraint(fields=['sid','book_dtno'],name='unique_together1')]

room_slot/templates/manager_dash/add-room.html
{% extends 'base/base.html'%}
{% block content%}
    <div class="row">
<div class="col l8 offset-l2 m10 offset-m1 s12">
<div class="card-panel">
      {% if messages %}
  {% for messsage in messages %}
  {% if messsage.tags == 'info' %}
 <div class='chip green white-text'>{{messsage}}</div>
 {% endif %}
  {% if messsage.tags == 'warning' %}
 <div class='chip red white-text'>{{messsage}}</div>
 {% endif %}
 <br>
  {% endfor %}
  {% endif %}
<div class="row">
<form class="col s12" method="POST" action="/user/add-room/new/" enctype="multipart/form-data">
{% csrf_token %}
      <div class="row">
        <div class="input-field col s12">  
          <input placeholder="Enter Room No" id="first_name" type="text" name="room_no">
          <label for="first_name">Room No</label>
        </div>
      </div>
      <div class="row">
      <div class="col s12">
       <label>Room Type</label>
  <select class="browser-default" name="room_type">
    <option value="Single Room">Single Room</option>
    <option value="Double Room">Double Room</option>
    <option value="Deluxe Room">Deluxe Room</option>
    <option value="Super Deluxe Room">Super Deluxe Room</option>

  </select>
      </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input type="text" name="price" id="price">
          <label for="price">Price</label>
        </div>
      </div>
      <div class="row">
 <div class="file-field input-field col s12">
     <div class="btn red lighten-2">
       <span><i class="material-icons left black-text text-lighten-1">image</i> Room Image</span>
       <input type="file" name="room_image">
     </div>
     <div class="file-path-wrapper">
       <input class="file-path validate" type="text">
     </div>
   </div>
      
      </div>
         <div class="row">
        <div class="input-field col s12">
          <input type="text" name="no_of_days_advance" id="no_of_days_advance">
          <label for="no_of_days_advance">No of days in advance</label>
        </div>
      </div>
         <div class="row">
        <div class="input-field col s12">
          <input type="text" name="start_day" id="start_day" class="datepicker">
          <label for="start_day">From when room will be available for booking</label>
        </div>
      </div>
      <div class="center">
      <input type="submit" class="btn green btn-large" value="Add Room">
      </div>
    </form>
</div>
</div>
</div>
    </div>
    <script>
     $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15, // Creates a dropdown of 15 years to control year,
    today: 'Today',
    clear: 'Clear',
    close: 'Ok',
    closeOnSelect: false // Close upon selecting a date,
  });
        
    </script>
{% endblock %}

room_slot/templates/manager_dash/edit-room.html
{% extends 'base/base.html'%}
{% block content%}
    <div class="row">
<div class="col l8 offset-l2 m10 offset-m1 s12">
<div class="card-panel">
<h4>Updating the Data for Room No: {{room.room_no}}</h4>
      {% if messages %}
  {% for messsage in messages %}
  {% if messsage.tags == 'info' %}
 <div class='chip green white-text'>{{messsage}}</div>
 {% endif %}
  {% if messsage.tags == 'warning' %}
 <div class='chip red white-text'>{{messsage}}</div>
 {% endif %}
 <br>
  {% endfor %}
  {% endif %}
<div class="row">
<form class="col s12" method="POST" action="/user/add-room/update/{{room.room_no}}/">
{% csrf_token %}
      <div class="row">
        <div class="input-field col s12">
          <input type="text" name="price" id="price" value="{{room.price}}"> 
          <label for="price">Price</label>
        </div>
      </div>
         <div class="row">
        <div class="input-field col s12">
          <input type="text" name="no_of_days_advance" id="no_of_days_advance" value="{{room.no_of_days_advance}}">
          <label for="no_of_days_advance">No of days in advance</label>
        </div>
      </div>
      <div class="center">
      <input type="submit" class="btn green btn-large" value="Update Room">
      </div>
    </form>
</div>
</div>
</div>
    </div>
{% endblock %}

room_slot/templates/manager_dash/index.html
{% extends 'base/base.html'%}
{% block content%} 
<link href="https://fonts.googleapis.com/css?family=Fredoka+One|Shadows+Into+Light&display=swap" rel="stylesheet"> 

    <div class="row">
    <div class="center" style="margin-top:2%">
          {% if messages %}
  {% for messsage in messages %}
  {% if messsage.tags == 'info' %}
 <div class='chip green white-text'>{{messsage}}</div>
 {% endif %}
  {% if messsage.tags == 'warning' %}
 <div class='chip red white-text'>{{messsage}}</div>
 {% endif %}
 <br>
  {% endfor %}
  {% endif %}
    </div>
<div class="col offset-l1 l4 offset-m1 m5 s6">
<div class="card-panel center">
<h5 style="font-family: 'Shadows Into Light', cursive;" class='blue-text'>Occupied Rooms Status</h5>
<h3 style="font-family: 'Fredoka One', cursive;">
{{booked}}
</h3>
</div>
</div>
<div class="col offset-l1 l4 m5 s6">
<div class="card-panel center">
<h5 style="font-family: 'Shadows Into Light', cursive;" class='blue-text'>Total Rooms to manage</h5>
<h3 style="font-family: 'Fredoka One', cursive;">
{{room_data.count}}
</h3>
</div>
</div>
<div class="col l8 offset-l2 m10 offset-m1 s12">
<div class="center">
<a class="btn green lighten-2" href="/user/add-room/new"">Add Rooms</a>
</div>
<h3 style="font-family: 'Fredoka One', cursive;" class="brown-text">Room Status</h3>
<div id="message">
</div>
{% if room_data %}
<table class="highlight bordered responsive-table">
        <thead class="red lighten-4">
          <tr>
              <th>Room No</th>
              <th>Room Type</th>
              <th>Price</th>
              <th>Customer Name</th>
              <th>Booked On</th>
              <th>Booking Data</th>
              <th>Edit</th>
              <th>Delete</th>
          </tr>
        </thead>
        <tbody>
        {% for room in room_data%}
                  <tr>
            <td>{{room.room_no}}</td>
            <td>{{room.room_type}}</td>
            <td>{{room.price}}</td>
            {% with data=room.booking_set.all.0 %}
            <td><a href="/user/dashboard/details/{{data.user_id.id}}/{{data.id}}">{{data.user_id.username}}</a></td>
            <td>{{data.booked_on}}</th>
            <td>
            {% if  room.is_available%}
            Available
            {% else %}
            {{data.start_day}} to {{data.end_day}}
            {% endif %}
            </td>
            <td><a class="btn blue" href="/user/add-room/update/{{room.room_no}}">Edit</a></td>
            <td><a class="btn red cancel-btn" href="" id="{{room.id}}">Delete</a></td>
            {% endwith %}
          </tr>
        {% endfor %}
        </tbody>
      </table>
{% else %}
<p>Sorry no rooom has been added by you, please add a room now <a href="/user/add-room/new">Here</a></p>
{% endif %}
</div>
    </div>
     <script>
    cancel_btn=document.querySelectorAll(".cancel-btn")
    cancel_btn.forEach((data)=>{
  data.addEventListener("click",(e)=>
    {
      e.preventDefault()
      id=e.target.id
   var xhttp = new XMLHttpRequest();
xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
 console.log(xhttp.responseText)
       document.getElementById("message").innerHTML = "<div class='chip green white-text'>"+xhttp.responseText+"</div>";
       window.setTimeout(function(){location.reload()},1000)
    }
};
xhttp.open("GET", "/delete-room/"+id, true);
xhttp.send();
    })
    })
    </script>
{% endblock %}